#!/bin/bash

echo "🔍 Checking which worker has routes attached"
echo "============================================="
echo ""
echo "This will help identify which worker is actually handling requests."
echo ""
echo "📋 Steps to check in Cloudflare Dashboard:"
echo ""
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Navigate to: Workers & Pages"
echo ""
echo "3. Check BOTH workers:"
echo "   a) hoopgeek-meta-injector"
echo "   b) hoopgeek-meta-injector-production"
echo ""
echo "4. For EACH worker, go to:"
echo "   → Triggers tab"
echo "   → Look for 'Routes' section"
echo ""
echo "5. Note which one has routes attached:"
echo "   - Should see: hoop-geek.com/* (or your domain)"
echo "   - Status: Active/Enabled"
echo ""
echo "📌 Most likely scenario:"
echo "   - ONE worker has routes attached (this is the one that works)"
echo "   - ONE worker has NO routes (this one doesn't respond)"
echo ""
echo "✅ Solution:"
echo "   1. Delete the worker WITHOUT routes (or keep it for testing)"
echo "   2. Make sure the worker WITH routes is up to date"
echo "   3. Always use: npx wrangler deploy --env production"
echo ""
echo "💡 The correct setup should be:"
echo "   - Worker name: hoopgeek-meta-injector"
echo "   - Environment: production (has routes)"
echo "   - Deploy command: npx wrangler deploy --env production"
echo ""

