import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    // Initialize Supabase client with service role key for admin operations
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const supabase = createClient(supabaseUrl, supabaseKey)

    // Get the authorization header
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      throw new Error('No authorization header')
    }

    // Create a client with the user's JWT
    const userSupabase = createClient(supabaseUrl, supabaseKey, {
      global: {
        headers: {
          Authorization: authHeader,
        },
      },
    })

    // Get the current user
    const { data: { user }, error: userError } = await userSupabase.auth.getUser()
    if (userError || !user) {
      throw new Error('Unauthorized')
    }

    // Parse request body
    const body = await req.json()
    const { 
      name, 
      description, 
      maxTeams, 
      scoringType, 
      teamName,
      rosterConfig,
      draftDate,
      salaryCapAmount,
      startersCount,
      startersMultiplier,
      rotationCount,
      rotationMultiplier,
      benchCount,
      benchMultiplier
    } = body

    // Validate required fields
    if (!name || !teamName || !maxTeams || !scoringType) {
      throw new Error('Missing required fields')
    }

    // Default roster configuration if not provided
    const defaultRosterConfig = {
      "PG": 1,
      "SG": 1,
      "SF": 1,
      "PF": 1,
      "C": 1,
      "G": 1,
      "F": 1,
      "UTIL": 3,
      "BENCH": 3,
      "IR": 1
    }

    // The invite code will be generated by the database function

    // Create league using the database function (use userSupabase to pass user's JWT)
    const { data: leagueId, error: leagueError } = await userSupabase
      .rpc('create_league_with_commissioner', {
        league_name: name,
        league_description: description || null,
        max_teams_count: maxTeams,
        scoring_type_val: scoringType,
        team_name_val: teamName,
        salary_cap_enabled_val: true,
        salary_cap_amount_val: salaryCapAmount || 200000000,
        lineup_frequency_val: 'daily',
        roster_config: rosterConfig || defaultRosterConfig,
        draft_date_val: draftDate || null,
        starters_count_val: startersCount || 5,
        starters_multiplier_val: startersMultiplier || 1.0,
        rotation_count_val: rotationCount || 5,
        rotation_multiplier_val: rotationMultiplier || 0.75,
        bench_count_val: benchCount || 3,
        bench_multiplier_val: benchMultiplier || 0.5
      })

    if (leagueError) {
      console.error('League creation error:', leagueError)
      throw new Error(`Failed to create league: ${leagueError.message}`)
    }

    // Get the created league details
    const { data: league, error: fetchError } = await userSupabase
      .from('leagues')
      .select(`
        *,
        league_members (
          id,
          team_name,
          is_commissioner,
          user_id
        )
      `)
      .eq('id', leagueId)
      .single()

    if (fetchError) {
      console.error('League fetch error:', fetchError)
      throw new Error(`Failed to fetch created league: ${fetchError.message}`)
    }

    console.log('Successfully created league:', league)

    return new Response(
      JSON.stringify({
        message: 'League created successfully',
        league: league
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      },
    )

  } catch (error) {
    console.error('Function error:', error)
    return new Response(
      JSON.stringify({ 
        error: error.message || 'Unknown error occurred',
        details: error.toString()
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      },
    )
  }
})